title = "clippt"

[[slides]]
source = """
# clippt

## A command-line based (TUI) presentation application.

https://github.com/janpipek/clippt
"""

[[slides]]
source = """
# Main features

- Simple TOML/JSON configuration.
- Many slide types.
- Run Python code or shell directly from the app.
- Build presentations programatically.
- Key shortcuts compatible with presenter hardware.
"""

[[slides]]
path = "markdown.md"

[[slides]]
type = "python"
source = """
# Press "." to run the code.

print(42)"""
title = "Example: A runnable Python slide"

[[slides]]
type = "python"
title = "Example: A Python slide running automatically"
source = """
for y in range(HEIGHT - 3):
    print ("#" * WIDTH)
"""
display_mode = "output"

[[slides]]
type = "shell"
source = """
# Press "." to run the code.

ls -la
"""
title = "Example: Runnable shell slide"

[[slides]]
path = "planets.csv"
title = "Example: data slide"

[[slides]]
path = "non-existent.py"
title = "File missing"

[[slides]]
path = "presentation.toml"
title = "Example: This presentation source"

[[slides]]
title = "An empty slide (just title)"

[[slides]]
title = "The end"
